#!/usr/bin/env python3

import sys

from rqt_gui.main import Main

plugin = 'conveyor_gui.conveyor_gui.GUI'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))

# sys.exit(main.main(standalone=plugin, plugin_argument_provider=Plot.add_arguments))
